### ISSUE TITLE
Wrong Label in Layers - Streams

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sparrow-california-js#17]
From cooperator:
>problems except for the name of the stream map layer for the CA application. The mapper describes it as "Pacific Northwest Streams". It should be named "California Streams".

**Comment by rstevensonUSGS** [comment]
I fixed this, I just need to make a new build for it. see screenshot. 
<img width="207" alt="ca streams" src="https://user-images.githubusercontent.com/22685263/49393109-93abec00-f6ed-11e8-9d5c-1075a7660ce1.PNG">

**Comment by rstevensonUSGS** [comment]
Updated Build
