### ISSUE TITLE
WIM Favicon

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/sparrow-california-js#8]
![image](https://user-images.githubusercontent.com/12058013/47676115-15aa7180-db92-11e8-8cb8-cf40682c86b2.png)

**Comment by HansVraga** [comment]
See WIM icon in National Dissolved Solids

**Comment by esmyers** [comment]
![image](https://user-images.githubusercontent.com/2495167/47676804-87cb8800-db8b-11e8-97e1-da3026d4da02.png)
faviconsmall.png should be in the images folder.

**Comment by esmyers** [comment]
@rstevensonUSGS check the href link to the icon on line 35 of the index.html.  I think there's a typo in the file path.
